version: "3.5"

services:
  node-red:
    image: nodered/node-red
    volumes:
      - /home/pi/.node-red:/data
    ports:
      - 1880:1880
   
  gpiod:
    image: gpiod:latest
    privileged: true
    restart: unless-stopped
#    volumes:
#      - /dev/mem:/dev/mem
#      - /dev/gpiomem:/dev/gpiomem
#      - /dev/i2c-1:/dev/i2c-1
