version: "3.5"

services:
  node-red:
    image: nodered/node-red
    volumes:
      - /home/pi/.node-red:/data
    ports:
      - 1880:1880
   
  gpiod:
    image: corbosman/node-red-gpiod:dev
    privileged: true
    restart: unless-stopped
